#finetune_config



general:
  model_name_or_path: 'THUDM/chatglm3-6b'  # 模型ID或本地路径
  # train_data_path: 'data_gen/zhouyi_dataset_handmade.csv'    # 训练数据路径
  train_data_path: 'data_gen/zhouyi_dataset_20240118_163659.csv'    # 训练数据路径(批量生成数据集）
  eval_data_path: None                     # 验证数据路径，如果没有则设置为None
  seed: 8                                 # 随机种子
  max_input_length: 512                    # 输入的最大长度
  max_output_length: 1536                  # 输出的最大长度
  lora_rank: 16                             # LoRA秩
  lora_alpha: 32                           # LoRA alpha值
  lora_dropout: 0.05                       # LoRA Dropout率
  prompt_text: ''                          # 所有数据前的指令文本

bnb:
  load_in_4bit: True
  bnb_4bit_quant_type: 'nf4',
  bnb_4bit_use_double_quant: True
  bnb_4bit_compute_dtype: _compute_dtype_map['bf16']